add missing libLLVM shared dependency
After restoring gallium static library dependencies
by reverting "pipe: use gallium loader function"
libLLVM shared library dependency is needed.

Fixes the following building errors:

[ 91% 3951/4296] target SharedLib: libgralloc_drm_32 (out/ta...ARIES/libgralloc_drm_intermediates/LINKED/libgralloc_drm.so)
FAILED: /bin/bash -c "prebuilts/clang/host/linux-x86/clang-2690385/bin/clang++ ..."
external/mesa/src/gallium/auxiliary/draw/draw_llvm.c:534: error: undefined reference to 'LLVMContextCreate'
external/mesa/src/gallium/auxiliary/draw/draw_llvm.c:534: error: undefined reference to 'LLVMContextDispose'
external/mesa/src/gallium/auxiliary/draw/draw_llvm.c:534: error: undefined reference to 'LLVMContextDispose'
...