gralloc_drm_pipe: change transfer_(un)map into texture_(un)map
Changes due to mesa 21.2 commit
eb74f977693 ("gallium: split transfer_(un)map into buffer_(un)map and texture_(un)map")

NOTE: texture_(un)map was found to be working,
buffer_map() has less arguments and does not build
and buffer_unmap() was causing crashes

Fixes the following building errors:

external/drm_gralloc/gralloc_drm_pipe.c:218:3: error: implicit declaration of function 'pipe_transfer_unmap' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                pipe_transfer_unmap(pm->context, buf->transfer);
                ^
external/drm_gralloc/gralloc_drm_pipe.c:218:3: note: did you mean 'pipe_buffer_unmap'?
external/mesa/src/gallium/auxiliary/util/u_inlines.h:384:1: note: 'pipe_buffer_unmap' declared here
pipe_buffer_unmap(struct pipe_context *pipe,
^
external/drm_gralloc/gralloc_drm_pipe.c:258:11: error: implicit declaration of function 'pipe_transfer_map' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                *addr = pipe_transfer_map(pm->context, buf->resource,
                        ^
external/drm_gralloc/gralloc_drm_pipe.c:258:11: note: did you mean 'pipe_buffer_map'?
external/mesa/src/gallium/auxiliary/util/u_inlines.h:373:1: note: 'pipe_buffer_map' declared here
pipe_buffer_map(struct pipe_context *pipe,
^
external/drm_gralloc/gralloc_drm_pipe.c:258:9: error: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Werror,-Wint-conversion]
                *addr = pipe_transfer_map(pm->context, buf->resource,
                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/drm_gralloc/gralloc_drm_pipe.c:281:2: error: implicit declaration of function 'pipe_transfer_unmap' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        pipe_transfer_unmap(pm->context, buf->transfer);
        ^
4 errors generated.