android: relax building errors due to warnings
To avoid the following building errors:

In file included from external/drm_gralloc/gralloc_drm_intel.c:42:
In file included from external/drm_gralloc/gralloc_drm_priv.h:28:
external/mesa/include/xf86drm.h:117:1: error: unused label 'success' [-Werror,-Wunused-label]
success:
^~~~~~~~
external/mesa/include/xf86drm.h:66:6: error: variable 'ver' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitial
ized]
        if (nbr_filters > 0 && filters == NULL)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/mesa/include/xf86drm.h:122:17: note: uninitialized use occurs here
        drmFreeVersion(ver);
                       ^~~
external/mesa/include/xf86drm.h:66:2: note: remove the 'if' if its condition is always false
        if (nbr_filters > 0 && filters == NULL)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/mesa/include/xf86drm.h:63:6: error: variable 'ver' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitial
ized]
        if (fd < 0)
            ^~~~~~
external/mesa/include/xf86drm.h:122:17: note: uninitialized use occurs here
        drmFreeVersion(ver);
                       ^~~
external/mesa/include/xf86drm.h:63:2: note: remove the 'if' if its condition is always false
        if (fd < 0)
        ^~~~~~~~~~~
external/mesa/include/xf86drm.h:69:2: note: variable 'ver' is declared here
        drmVersionPtr ver = drmGetVersion(fd);
        ^
3 errors generated.