gralloc_drm_pipe: rename pipe_transfer_usage -> pipe_map_flags
Changes due to mesa 20.3 commit
358606855 ("gallium: rename pipe_transfer_usage -> pipe_map_flags")

Fixes the following building error:

external/drm_gralloc/gralloc_drm_pipe.c:246:28: error: variable has incomplete type 'enum pipe_transfer_usage'
                enum pipe_transfer_usage usage;
                                         ^
external/drm_gralloc/gralloc_drm_pipe.c:246:8: note: forward declaration of 'enum pipe_transfer_usage'
                enum pipe_transfer_usage usage;
                     ^
1 error generated.

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>