add back GRALLOC_MODULE_PERFORM_{ENTER,LEAVE}_VT enums
libsurfaceflinger requires GRALLOC_MODULE_PERFORM_{ENTER,LEAVE}_VT
defined in gralloc_drm.h, fixes the following building errors:

frameworks/native/services/surfaceflinger/DisplayDevice.cpp:273:29:
error: use of undeclared identifier 'GRALLOC_MODULE_PERFORM_LEAVE_VT'
            gr->perform(gr, GRALLOC_MODULE_PERFORM_LEAVE_VT);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
frameworks/native/services/surfaceflinger/DisplayDevice.cpp:278:29:
error: use of undeclared identifier 'GRALLOC_MODULE_PERFORM_ENTER_VT'
            gr->perform(gr, GRALLOC_MODULE_PERFORM_ENTER_VT);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

Fixes: 642a7755 ("drm_gralloc: Use render node") for android-x86 build