HACK: move gralloc_drm_bo_{lock,unlock}() to gralloc.cpp (v2)
This is a workaround to the following building errors:

external/drm_gralloc/gralloc.cpp:126: error: undefined reference to 'gralloc_drm_bo_lock'
external/drm_gralloc/gralloc.cpp:153: error: undefined reference to 'gralloc_drm_bo_lock'
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)
..
external/drm_gralloc/gralloc.cpp:251: error: undefined reference to 'gralloc_drm_bo_unlock'
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

To be removed as soon a better way to build is available

(v2) Hack applied to oreo-x86 branch moved to cpp