gralloc_drm_pipe: rename PIPE_TRANSFER_* -> PIPE_MAP_*
Changes due to mesa 20.3 commit
22253e6b6 ("gallium: rename PIPE_TRANSFER_* -> PIPE_MAP_*")

Fixes the following building errors:

external/drm_gralloc/gralloc_drm_pipe.c:248:11: error: use of undeclared identifier 'PIPE_TRANSFER_READ'
                usage = PIPE_TRANSFER_READ;
                        ^
external/drm_gralloc/gralloc_drm_pipe.c:250:13: error: use of undeclared identifier 'PIPE_TRANSFER_WRITE'
                        usage |= PIPE_TRANSFER_WRITE;
                                 ^
2 errors generated.

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>